config/routes.rb
Rails.application.routes.draw do
  # User Routes
  resources :users, only: %i[create show]
  get 'sign_up', to: 'users#sign_up', as: 'sign_up'
  # Session Routes
  scope :sessions, path: '/' do
    get 'sign_in', to: 'sessions#sign_in'
    post 'sessions', to: 'sessions#authenticate'
    delete 'sessions', to: 'sessions#destroy'
  end

  # Defines the root path route ("/")
  root 'static#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  bitmask_enum role: %i[standard admin super_admin], flag_prefix: 'role'

  def has_admin_perms?
    role_admin? || role_super_admin?
  end

  def super_admin?
    role_super_admin?
  end

  def admin?
    role_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :signed_in?, :current_user, :admin?

  def current_user
    return unless session[:user_id]

    @user = User.find(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  def admin?
    return unless signed_in?

    current_user.has_admin_perms?
  end

  def authorized?
    redirect_to sign_in_path unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def authenticate
    @user = User.find_by(username: params[:session][:login]) || User.find_by(email: params[:session][:login])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized?, only: [:show]
  def sign_up
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to root_path
    else
      redirect :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Ready Boilerplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="w-screen h-screen flex flex-col">
    <%= render partial: "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="global">
  <div class="logo"><%= link_to "Rails Ready", root_path %></div>
  <nav>
    <% if signed_in? %>
      <%= link_to "Sign Out", sessions_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Sign In", sign_in_path %>
      <div class="px-1">/</div>
      <%= link_to "Sign Up", sign_up_path %>
    <% end %>
  </nav>
</header>

app/views/users/show.html.erb
<h1>Welcome</h1>
<p>Hello <%= current_user.username %>!</p>

app/views/users/sign_up.html.erb
<div class="w-full h-full flex flex-col items-center justify-center">
  <h1>Sign Up</h1>
  <%= form_for @user, method: :post, html: { class: "flex flex-col space-y-2" } do |f| %>
    <div class="flex flex-col space-y-1">
      <%= f.label :username %>
      <%= f.text_field :username, placeholder: "Username", class: 'border rounded-full px-3 py-1' %>
    </div>
    <div class="flex flex-col space-y-1">
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "Email", class: 'border rounded-full px-3 py-1' %>
    </div>
    <div class="flex flex-col space-y-1">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Password", class: 'border rounded-full px-3 py-1' %>
    </div>
    <div class="flex flex-col space-y-1">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'border rounded-full px-3 py-1' %>
    </div>
    <%= f.submit "Create Account", class: 'bg-indigo-500 text-white font-semibold px-3 py-1 w-full rounded-full' %>
    <small class="text-center">Already have an account? <%= link_to "Sign In", sign_in_path, class: 'underline text-indigo-500' %></small>
  <% end %>
</div>